name: frontend CI

on:
  push:
    branches:
      - main 
  pull_request:
    branches:
      - main

jobs:
  frontend:
    runs-on: ubuntu-latest
    timeout-minutes: 180

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Node.js for Frontend
        uses: actions/setup-node@v2
        with:
          node-version: 19

      - name: Install Frontend Dependencies
        working-directory: ./frontend
        run: npm ci

      - name: Build Frontend
        working-directory: ./frontend
        run: npm run dev 

      - name: Run Frontend Tests
        working-directory: ./frontend
        run: npm start 
